### ISSUE TITLE
Get rid of this exemption in the chats (occurs often)

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1116]
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:  Exception from sub chats.by_id id cPuoSnhaoSb7vHReq Error: Match error: Expected string, got null
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at exports.check (packages/check.js:57:15)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].<anonymous> (packages/partup-server/publications/chats.js:157:5)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at packages/matb33_collection-hooks.js:307:21
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 13 12:09:32 34.253.162.141 meteor-a63f9a0fc577:  Sanitized and reported to the client as: Match failed [400]

**Comment by ralphboeije** [comment]
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0: Exception from sub updates.from_partup id g9ekB6zw8Fs3rSFC4 Error: Match error: Expected string, got null
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at exports.check (packages/check.js:57:15)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object].<anonymous> (packages/partup-server/publications/updates.js:58:5)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at packages/matb33_collection-hooks.js:307:21
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0:     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 13 12:24:08 34.253.70.110 meteor-1f899123ceb0: Sanitized and reported to the client as: Match failed [400]

**Comment by ralphboeije** [comment]
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:  error:  Error: Swarm_could_not_be_found [404]
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].Mongo.Collection.findOneOrFail (packages/partup-server/helpers/collection.js:16:15)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at [object Object].Meteor.methods.swarms.get_related_uppers (packages/partup-server/methods/swarms/swarms_methods.js:331:32)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at packages/ddp-server/livedata_server.js:719:19
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at packages/ddp-server/livedata_server.js:717:40
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at packages/ddp-server/livedata_server.js:715:46
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at new wrappedPromise (/app/node_modules/newrelic/lib/instrumentation/promise.js:156:20)
Jun 13 12:03:06 34.253.162.141 meteor-a63f9a0fc577:      at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)

**Comment by ralphboeije** [comment]
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Exception from sub partups.one id 2GrrTMJJrDT3bPCbT Error: Match error: Expected string, got null
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at exports.check (packages/check.js:57:15)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/partup-server/publications/partups.js:237:5)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at packages/matb33_collection-hooks.js:307:21
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Sanitized and reported to the client as: Match failed [400]
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Exception from sub activities.from_partup id NKogSkvCEif7Wpgtk Error: Match error: Expected string, got null
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at exports.check (packages/check.js:57:15)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/partup-server/publications/activities.js:8:5)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at packages/matb33_collection-hooks.js:307:21
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Sanitized and reported to the client as: Match failed [400]
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Exception from sub updates.from_partup id gs9RbXutqtvBg6DJZ Error: Match error: Expected string, got null
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at exports.check (packages/check.js:57:15)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/partup-server/publications/updates.js:58:5)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at packages/matb33_collection-hooks.js:307:21
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Sanitized and reported to the client as: Match failed [400]
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Exception from sub board.for_partup_id id 4qWibRCQMK6cBYhxC Error: Match error: Expected string, got null
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at exports.check (packages/check.js:57:15)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/partup-server/publications/boards.js:2:5)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].prepareOptions (packages/reywood-publish-composite.js:461:43)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].<anonymous> (packages/reywood-publish-composite.js:429:46)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at packages/matb33_collection-hooks.js:307:21
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8:     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock.js:71:22)
Jun 15 13:28:34 52.19.81.166 meteor-3e2f5e73f7f8: Sanitized and reported to the client as: Match failed [400]

**Comment by noelheesen** [comment]
I have found one error: `chats.by_id.for_web expected string but got null`.
The solution is in `OneOnOneChat.js` `line 117`.
It does not check if one of the values exists, it should by modified like this:
```
if (chatId !== hash) {
            if (chatId === undefined && hash === undefined) {
                return;
            }
```

Working on another issue so I'll do this one after. I suspect the other Match error exceptions also miss checks like these before subscribing.
