### ISSUE TITLE
API_ROOT_URL not set in ft-recommended-partups-dev

### ISSUE THREAD

**Issue by vanderGoes** [part-up/part-up#658]
@wouterd This error occurs when opening the recommended part-ups modal. Is this because this variable is called just ROOT_URL in the API docker-compose.yml file? I tried to test it, but no success yet.

`meteor_1 | Sun, 04 Sep 2016 12:16:50 GMT connect deprecated res.headerSent: use standard res.headersSent at npm/node_modules/meteor/simple_json-routes/node_modules/connect/lib/proto.js:127:22
meteor_1 | ERROR: API_ROOT_URL not set.
meteor_1 | TypeError: Cannot read property 'find' of undefined
meteor_1 |     at [object Object].<anonymous> (packages/partup-server/routes/composite.js:11:1)
meteor_1 |     at boundNext (packages/iron_middleware-stack/lib/middleware_stack.js:251:1)
meteor_1 |     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
meteor_1 |     at packages/meteor/dynamics_nodejs.js:123:1
meteor_1 |     at [object Object].urlencodedParser (/app/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:84:40)
meteor_1 |     at packages/iron_router/lib/router.js:277:1
meteor_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
meteor_1 |     at [object Object].hookWithOptions (packages/iron_router/lib/router.js:276:1)
meteor_1 |     at boundNext (packages/iron_middleware-stack/lib/middleware_stack.js:251:1)
meteor_1 |     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)`

**Comment by vanderGoes** [comment]
Nope, doesn't look like the solution.

`Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11: getRecommendedIds error: TypeError: Cannot read property 'partUpIds' of null 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11: TypeError: Cannot read property 'find' of undefined 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at [object Object].<anonymous> (packages/partup-server/routes/composite.js:11:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at boundNext (packages/iron_middleware-stack/lib/middleware_stack.js:251:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at packages/meteor/dynamics_nodejs.js:123:1 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at [object Object].urlencodedParser (/app/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:84:40) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at packages/iron_router/lib/router.js:277:1 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at [object Object].hookWithOptions (packages/iron_router/lib/router.js:276:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at boundNext (packages/iron_middleware-stack/lib/middleware_stack.js:251:1) 
Sep 05 00:16:31 meteor-1 meteor-1.stg-ft-recommended-partups-dev.470d5b11:     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) `

**Comment by vanderGoes** [comment]
The old skool find isn't working either. Enough for today :(

**Comment by vanderGoes** [comment]
The API works correctly.
I think the problem is related to NPM or google-http-java-client library.

@tlimpanont or @wouterd do you have an idea?

**Comment by vanderGoes** [comment]
All right, I fixed the error with the simple commit [81a1733](https://github.com/part-up/part-up/commit/81a1733aeb095f38ddac6baf2fbb30055ed0eddf). But the modal is still empty. More tomorrow.
