### ISSUE TITLE
in partups.one subscription, a find on images sometimes produces match error

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/part-up#764]
maybe has to do with a nullcheck on image id in the subscription?

report from the production server logs:

```
Exception from sub partups.one id rbuiG2i8mtc8H7gu5 Error: Match error: Expected string, got null
    at exports.check (packages/check/match.js:34:1)
    at Subscription.Meteor.publish.Images.find._id (packages/partup-server/publications/partups.js:361:1)
    at Subscription.prepareOptions (packages/reywood-publish-composite/lib/publish_composite.js:37:1)
    at Subscription.<anonymous> (packages/reywood-publish-composite/lib/publish_composite.js:5:1)
    at packages/matb33_collection-hooks/collection-hooks.js:275:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
    at Subscription.MeteorX.Subscription._runHandler (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:55:1)
Sanitized and reported to the client as: Match failed [400]
```

**Comment by ralphboeije** [comment]
I noticed that this one causes some performance issues when loading tribe/slug/partups and discover and home pages
